In [12]:
#Softmax example - Logistic regression classifier(binary labels)
#Softmax (aka normalized exponential function) squashes a K-dimensional
#vector z with arbitrary values to a K-dimensional vector of real values
#in the range (0,1) that add up to one

#Computing Softmax scores turns them into probabilities

#Example - 1 dimensional array
#Each of the numbers represents a class
scores = [3.0, 1.0, 0.2]

import numpy as np

def softmax(x):
    """Compute softmax values for x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

print(softmax(scores))

#Plot softmax curves
import matplotlib.pyplot as plt
x = np.arange(-2.0, 6.0, 0.1)
scores = np.vstack([x, np.ones_like(x), 0.2 * np.ones_like(x)])

plt.plot(x, softmax(scores).T, linewidth=2)
plt.show

[ 0.8360188   0.11314284  0.05083836]


<function matplotlib.pyplot.show>

In [8]:
#Now, let's do a 2-dimensional array
scores = ([[1, 2, 3, 6],
          [2, 4, 5, 6],
          [3, 8, 7, 6]])

softmax (scores)

array([[ 0.09003057,  0.00242826,  0.01587624,  0.33333333],
       [ 0.24472847,  0.01794253,  0.11731043,  0.33333333],
       [ 0.66524096,  0.97962921,  0.86681333,  0.33333333]])

In [10]:
#Now, if you multiply the scores by 10, the softmax scores/probabilities get very close 
#to either 0 or 1
scores = np.array([3.0, 1.0, 0.2])
print(softmax(scores *10))

[  9.99999998e-01   2.06115362e-09   6.91440009e-13]


In [11]:
#Multiply the scores by 10. What happens?
scores = np.array([3.0, 1.0, 0.2])
print(softmax(scores / 10))

#The scores get closer to a uniform distribution

[ 0.38842275  0.31801365  0.2935636 ]


In [ ]:
#This means that if we increase size of outputs (i.e.-multiply by 10), 
#the classifier becomes very sure of its accuracy

In [16]:
#Calculating Numerical Stability
#Optimally, we want our values to have 0 mean and equal variance
#whenever possible

In [ ]:
#Transforming Images into Numerical values
#Normalize by take pixel number of image, (R-128)/128, (G-128)/128, (B-128)/128
